https://www.runoob.com/python3/python3-date-time.html
jinwu12/python pull request #13
Opened 2022-03-21 14:39 UTC by jinwu12

日期和时间

2022-03-21 15:57 UTC, jewforice-openwrt requested changes
利用面向对象的方式实现以下功能：
1. 基类将传入参数的时间（默认为当前时区）转换为目标时区的时间，并打印原始时间+原始时区、目标时间、目标时区。
2. 子类1在基类的基础上再打印原始和目标时间的时间戳
3. 子类2在基类的基础上再打印输入的时间对应的UTC0时区的时间和时间戳

2022-03-21 15:59 UTC, jewforice requested changes
利用面向对象的方式实现以下功能：
1. 基类将传入参数的时间（默认为当前时区）转换为目标时区的时间，并打印原始时间+原始时区、目标时间、目标时区。
2. 子类1在基类的基础上再打印原始和目标时间的时间戳
3. 子类2在基类的基础上再打印输入的时间对应的UTC0时区的时间和时间戳

2022-03-23 14:34 UTC, jewforice commented on __pycache__/ex24.py
> +    now_tz=int(time.timezone/3600)
这句话是啥意思？为啥要除以3600？

2022-03-23 14:34 UTC, jewforice commented on __pycache__/ex24.py
> +change3.cgtz()
输出的结果都备注出来看看

2022-03-24 06:50 UTC, jinwu12 commented on __pycache__/ex24.py
> +    now_tz=int(time.timezone/3600)
这个属性是距离格林威治的偏移秒数，除以3600秒才是小时表示的时区

2022-03-27 09:01 UTC, jewforice approved these changes
OK

2022-03-27 09:01 UTC, merged