https://www.runoob.com/python3/python3-basic-operators.html
jinwu12/python pull request #4
Opened 2022-02-21 12:32 UTC by jinwu12

运算符

2022-02-21 12:44 UTC, jewforice reviewed
每个新的小节搞一个新的文件吧

2022-02-21 12:47 UTC, jewforice requested changes

2022-02-21 12:47 UTC, jewforice commented on ex2.py
>  c5=b**a
这个运算都没有赋值啊

2022-02-21 12:47 UTC, jewforice commented on ex2.py
> +#结果 F，t，t
结果F，t，t是啥意思？

2022-02-21 12:47 UTC, jewforice commented on ex2.py
> +#0,23 23
这个0，23，23又是啥意思？

2022-02-21 14:20 UTC, jinwu12 commented on ex2.py
> +#结果 F，t，t
fause和ture

2022-02-21 14:23 UTC, jinwu12 commented on ex2.py
>  c5=b**a
不是20的立方吗

2022-02-21 14:51 UTC, jewforice requested changes
注释写清楚具体下面的代码是干嘛用的，还有运行结果，光整几个值看不懂啊

2022-02-22 12:53 UTC, jewforice approved these changes
OK

2022-02-22 12:56 UTC, merged